# Sample pd.DataFrame

In [2]:
# Importando as bibliotecas
import os
os.chdir("aula_teorica")

from joblib import load, dump
import pandas as pd

In [3]:
# Importando o banco
# dump(df_10, './data/05_aula_df_10')
df_14 = load('./data/05_aula_df_14')

df_14.head()

,indep_2,indep_3_max,indep_3_min,indep_4_min,indep_4_med,indep_4_max,target,linear_simples,linear_multi,svm,nb,NN
53,24.36,1,0,0,0,1,41,41.772154,42.144690,41,41,19.047935
93,8.05,0,1,0,1,0,9,17.536860,16.687991,9,23,19.001783
20,19.92,1,0,0,0,1,36,35.174686,35.667611,41,41,19.047298
177,7.73,1,0,1,0,0,13,17.061367,17.884818,9,17,18.999596
26,6.21,1,0,1,0,0,17,14.802774,15.667440,18,17,18.984955

In [4]:
# Importando
df_10 = load('./data/05_aula_df_10')

df_10.head()

,indep_1,indep_2,indep_3_max,indep_3_min,indep_4_min,indep_4_med,indep_4_max,target,k_means,DBSCAN_1,DBSCAN_2,NN_k_means,k_NN,log_reg,SVM,dec_tree,random_forest,gbm,nb,NN
53,41,24.36,1,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,0
93,9,8.05,0,1,0,1,0,0,1,1,1,0,0,1,0,0,0,0,0,0
20,36,19.92,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
177,13,7.73,1,0,1,0,0,1,1,1,1,1,1,1,0,0,0,0,0,0
26,17,6.21,1,0,1,0,0,0,1,1,1,0,0,1,0,0,0,0,0,0

In [5]:
def train_valid_test_df_split(
        df: pd.DataFrame,
        indep: list,
        target: str = "target",
        frac_valid: float = 0.2,
        frac_test: float = 0.13) -> tuple:
    '''
    Função que divide o DataFrame em treino, teste e validação
    e separa as colunas independentes e a coluna alvo.
    Esta função divide o DataFrame em três partes: treino, teste e validação,
    e separa as colunas independentes e a coluna alvo.

    Parameters
    ----------
    df : pd.DataFrame
        DataFrame a ser dividido.
    indep : list
        Lista de colunas independentes.
    target : str, optional
        Nome da coluna alvo. Default é "target".
    frac_valid : float, optional
        Proporção do DataFrame a ser usado como validação. Default é 0.2.
    frac_test : float, optional
        Proporção do DataFrame a ser usado como teste. Default é 0.13.
    
    Returns
    -------
    tuple
        Retorna uma tupla contendo:
        - df_train: DataFrame de treino.
        - df_valid: DataFrame de validação.
        - df_test: DataFrame de teste.
        - X_train: DataFrame de treino com colunas independentes.
        - X_valid: DataFrame de validação com colunas independentes.
        - X_test: DataFrame de teste com colunas independentes.
        - y_train: Série alvo de treino.
        - y_valid: Série alvo de validação.
        - y_test: Série alvo de teste.
    '''
    index = df.sample(frac=frac_valid, random_state=42).index
    df_train = df.loc[[i for i in df.index if i not in index], :]
    df_valid = df.loc[index, :]

    index = df_train.sample(frac=frac_test, random_state=42).index
    df_train = df_10.loc[[i for i in df_train.index if i not in index], :]
    df_test = df_10.loc[index, :]

    X_train = df_train.loc[:, indep].copy()
    X_valid = df_valid.loc[:, indep].copy()
    X_test = df_test.loc[:, indep].copy()

    y_train = df_train.loc[:, target].copy()
    y_valid = df_valid.loc[:, target].copy()
    y_test = df_test.loc[:, target].copy()

    linha = "-"*10
    print(linha)
    print(f"df_train: {df_train.shape}")
    print(f"df_valid: {df_valid.shape}")
    print(f"df_test: {df_test.shape}")

    print(linha)
    print(f"X_train: {X_train.shape}")
    print(f"X_valid: {X_valid.shape}")
    print(f"X_test: {X_test.shape}")

    print(linha)
    print(f"y_train: {y_train.shape}")
    print(f"y_valid: {y_valid.shape}")
    print(f"y_test: {y_test.shape}")

    print(linha)
    print(f"Train: {df_train.shape[0]/df_10.shape[0]:.0%}")
    print(f"Valid: {df_valid.shape[0]/df_10.shape[0]:.0%}")
    print(f"Test: {df_test.shape[0]/df_10.shape[0]:.0%}")

    return (
        df_train,
        df_valid,
        df_test,
        X_train,
        X_valid,
        X_test,
        y_train,
        y_valid,
        y_test
    )

In [6]:
df_10.columns[[0, 1, 2, 3, 4, 5, 6]]

Index(['indep_1', 'indep_2', 'indep_3_max', 'indep_3_min', 'indep_4_min',
       'indep_4_med', 'indep_4_max'],
      dtype='object')

In [7]:
indep = df_10.columns[[0, 1, 2, 3, 4, 5, 6]]
df_10_train, df_10_test, df_10_valid, X_test, X_train, X_valid, y_test, y_train, y_valid = train_valid_test_df_split(df=df_10, indep=indep)

----------
df_train: (70, 20)
df_valid: (20, 20)
df_test: (10, 20)
----------
X_train: (70, 7)
X_valid: (20, 7)
X_test: (10, 7)
----------
y_train: (70,)
y_valid: (20,)
y_test: (10,)
----------
Train: 70%
Valid: 20%
Test: 10%

In [8]:
X_test.head()

,indep_1,indep_2,indep_3_max,indep_3_min,indep_4_min,indep_4_med,indep_4_max
20,36,19.92,1,0,0,0,1
177,13,7.73,1,0,1,0,0
0,21,6.37,0,1,1,0,0
21,31,12.16,1,0,0,1,0
179,16,7.68,1,0,1,0,0

In [9]:
y_test.head()

20     0
177    1
0      0
21     0
179    1
Name: target, dtype: int64

# Sample Sklearn

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X = df_10[indep]
y = df_10['target']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)
X_test, X_valid, y_test, y_valid = train_test_split(X_test, y_test, test_size=0.66, random_state=42)

print('-'*10)
print(f"X_train: {X_train.shape}")
print(f"X_valid: {X_valid.shape}")
print(f"X_test: {X_test.shape}")
print('-'*10)
print(f"y_train: {y_train.shape}")
print(f"y_valid: {y_valid.shape}")
print(f"y_test: {y_test.shape}")

----------
X_train: (70, 7)
X_valid: (20, 7)
X_test: (10, 7)
----------
y_train: (70,)
y_valid: (20,)
y_test: (10,)

# Sample fast_ml

In [15]:
!pip freeze | grep fast

fast-ml==3.68
fastjsonschema==2.21.2

In [16]:
from fast_ml.model_development import train_valid_test_split

In [17]:
X_train, y_train, X_valid, y_valid, X_test, y_test = train_valid_test_split(
    df_10,
    target='target', 
    train_size=0.7, 
    valid_size=0.2, 
    test_size=0.1, 
    random_state=42
)

print('-'*10)
print(f"X_train: {X_train.shape}")
print(f"X_valid: {X_valid.shape}")
print(f"X_test: {X_test.shape}")
print('-'*10)
print(f"y_train: {y_train.shape}")
print(f"y_valid: {y_valid.shape}")
print(f"y_test: {y_test.shape}")

----------
X_train: (70, 19)
X_valid: (20, 19)
X_test: (10, 19)
----------
y_train: (70,)
y_valid: (20,)
y_test: (10,)

# Sample Numpy

In [18]:
import numpy as np

In [19]:
train_size = int(len(df_10)*.4)
test_size = int(len(df_10)*.1)

print(f"Train size: {train_size}")
print(f"Test size: {test_size}")

Train size: 40
Test size: 10

In [20]:
train_size = int(len(df_10)*.22)
test_size = int(len(df_10)*.10)

target = 'target'
index = np.random.choice(df_10.index, size=train_size, replace=False)
df_train = df_10.loc[[i for i in df_10.index if i not in index], :]
df_valid = df_10.loc[index, :]

index = np.random.choice(df_10.index, size=test_size, replace=False)
df_train = df_10.loc[[i for i in df_train.index if i not in index], :]
df_test = df_10.loc[index, :]

X_train = df_train.loc[:, indep].copy()
X_valid = df_valid.loc[:, indep].copy()
X_test = df_test.loc[:, indep].copy()

y_train = df_train.loc[:, target].copy()
y_valid = df_valid.loc[:, target].copy()
y_test = df_test.loc[:, target].copy()

print('-'*10)
print(f"X_train: {X_train.shape}")
print(f"X_valid: {X_valid.shape}")
print(f"X_test: {X_test.shape}")
print('-'*10)
print(f"y_train: {y_train.shape}")
print(f"y_valid: {y_valid.shape}")
print(f"y_test: {y_test.shape}")

----------
X_train: (70, 7)
X_valid: (22, 7)
X_test: (10, 7)
----------
y_train: (70,)
y_valid: (22,)
y_test: (10,)