In [1]:
from joblib import load
import pandas as pd
from ydata_profiling import ProfileReport

C:\Users\gfsil\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
df = load('./data/df_gera_aula_04')
df.head()

   num_cont num_disc      cat_nomi cat_ordi
0  1.993428      3.0  anhalouidine     midi
1  0.723471      2.0          joke     maxi
2  2.295377      1.0   orthobiosis     maxi
3  4.046060     -1.0      takedown    micro
4  0.531693      2.0     becrimson     midi

In [3]:
profile = ProfileReport(df, title="Profiling Report")
profile.to_file("./data/df_gera_aula_04_report.html")

100%|██████████| 4/4 [00:00<00:00,  9.04it/s]0<00:01,  4.00it/s, Describe variable: cat_ordi]
Summarize dataset: 100%|██████████| 14/14 [00:02<00:00,  4.83it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:04<00:00,  4.62s/it]
Render HTML: 100%|██████████| 1/1 [00:02<00:00,  2.14s/it]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 85.46it/s]

In [4]:
df = load('./data/df_no_nan_aula_04')
df.head()

   num_cont  num_disc      cat_nomi cat_ordi
0  1.993428         3  anhalouidine     midi
1  0.723471         2          joke     maxi
2  2.295377         1   orthobiosis     maxi
3  4.046060        -1      takedown    micro
4  0.531693         2     becrimson     midi

In [5]:
profile = ProfileReport(df, title="Profiling Report")
profile.to_file("./data/df_no_nan_aula_04_report.html")

100%|██████████| 4/4 [00:00<00:00, 34.79it/s]0<00:00, 14.90it/s, Describe variable: cat_ordi]
Summarize dataset: 100%|██████████| 17/17 [00:02<00:00,  7.46it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:04<00:00,  4.86s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  2.05it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 70.51it/s]

In [6]:
df = load('./data/df_dummies_qcut_aula_04')
df.head()

,num_cont,num_disc,cat_ordi_maxi,cat_ordi_micro,cat_ordi_midi,cat_ordi_mini,cat_nomi,cat_nomi_len_qcut_min,cat_nomi_len_qcut_25%,cat_nomi_len_qcut_50%,cat_nomi_len_qcut_75%
0,1.993428,3,0,0,1,0,anhalouidine,0,0,0,1
1,0.723471,2,1,0,0,0,joke,1,0,0,0
2,2.295377,1,1,0,0,0,orthobiosis,0,0,1,0
3,4.046060,-1,0,1,0,0,takedown,0,1,0,0
4,0.531693,2,0,0,1,0,becrimson,0,1,0,0

In [7]:
profile = ProfileReport(df, title="Profiling Report")
profile.to_file("./data/df_dummies_qcut_aula_04_report.html")

100%|██████████| 11/11 [00:00<00:00, 79.00it/s]<00:01,  8.52it/s, Describe variable: cat_nomi_len_qcut_75%]
Summarize dataset: 100%|██████████| 24/24 [00:03<00:00,  6.07it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:10<00:00, 10.63s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  1.70it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 46.78it/s]