In [1]:
# !pip install ydata-profiling util-gfsilveira

In [2]:
import os
from util import utils as ut

from joblib import load
import pandas as pd
from ydata_profiling import ProfileReport

c:\Users\gfsil\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
C:\Users\gfsil\AppData\Local\Temp\ipykernel_29628\1662029541.py:6: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

In [3]:
lista_df = ["./data/"+i for i in os.listdir("./data") if not i.endswith(".html") and not i.endswith(".txt")]
ut.printLis(lista_df)

-------------
-=< Lista >=-
-------------
0 -> ./data/00_aula_dados
1 -> ./data/00_aula_df
2 -> ./data/00_aula_df_1
3 -> ./data/00_aula_df_2
4 -> ./data/00_aula_df_nova
5 -> ./data/01_aula_dados
6 -> ./data/01_aula_df
7 -> ./data/01_aula_df_1
8 -> ./data/01_aula_df_2
9 -> ./data/01_aula_df_nova
10 -> ./data/04_aula_df_dummies_qcut
11 -> ./data/04_aula_df_final
12 -> ./data/04_aula_df_gera
13 -> ./data/04_aula_df_gera.csv
14 -> ./data/04_aula_df_gera.db
15 -> ./data/04_aula_df_gera_DB.db
16 -> ./data/04_aula_df_no_nan
17 -> ./data/05_aula_df
18 -> ./data/05_aula_df_1
19 -> ./data/05_aula_df_10
20 -> ./data/05_aula_df_11
21 -> ./data/05_aula_df_12
22 -> ./data/05_aula_df_13
23 -> ./data/05_aula_df_14
24 -> ./data/05_aula_df_2
25 -> ./data/05_aula_df_3
26 -> ./data/05_aula_df_4
27 -> ./data/05_aula_df_5
28 -> ./data/05_aula_df_6
29 -> ./data/05_aula_df_7
30 -> ./data/05_aula_df_8
31 -> ./data/05_aula_df_9
32 -> ./data/06_aula_df_biomarc
33 -> ./data/06_aula_df_cells
34 -> ./data/06_aula_df_variaveis

# 04_aula_df_gera

In [4]:
def gerador_reporte(c: int) -> None:
    '''
        Gera um relatório de perfilamento para o dataframe especificado
        pelo índice c na lista de dataframes.
        O relatório é salvo como um arquivo HTML.
            Parametros:
                c (int): Índice do dataframe na lista de dataframes.
            Retorna:
                None
    '''
    df = load(lista_df[c])
    display(lista_df[c])
    display(df.head())
    profile = ProfileReport(df, title="Profiling Report")
    profile.to_file(lista_df[c]+"_report.html")

    return None

In [5]:
gerador_reporte(c=12)

'./data/04_aula_df_gera'

   num_cont num_disc      cat_nomi cat_ordi
0  1.993428      3.0  anhalouidine     midi
1  0.723471      2.0          joke     maxi
2  2.295377      1.0   orthobiosis     maxi
3  4.046060     -1.0      takedown    micro
4  0.531693      2.0     becrimson     midi

100%|██████████| 4/4 [00:00<00:00, 134.23it/s]<?, ?it/s, Describe variable: cat_ordi]
Summarize dataset: 100%|██████████| 18/18 [00:00<00:00, 23.93it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:01<00:00,  1.04s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  5.19it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 154.71it/s]

# 04_aula_df_no_nan

In [6]:
gerador_reporte(c=16)

'./data/04_aula_df_no_nan'

   num_cont  num_disc      cat_nomi cat_ordi
0  1.993428         3  anhalouidine     midi
1  0.723471         2          joke     maxi
2  2.295377         1   orthobiosis     maxi
3  4.046060        -1      takedown    micro
4  0.531693         2     becrimson     midi

100%|██████████| 4/4 [00:00<00:00, 89.42it/s]0<00:00, 36.32it/s, Describe variable: cat_ordi]
Summarize dataset: 100%|██████████| 17/17 [00:00<00:00, 20.88it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:00<00:00,  1.04it/s]
Render HTML: 100%|██████████| 1/1 [00:00<00:00, 18.21it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 199.69it/s]

# 04_aula_df_dummies_qcut

In [7]:
gerador_reporte(c=10)

'./data/04_aula_df_dummies_qcut'

,num_cont,num_disc,cat_ordi_maxi,cat_ordi_micro,cat_ordi_midi,cat_ordi_mini,cat_nomi,cat_nomi_len_qcut_min,cat_nomi_len_qcut_25%,cat_nomi_len_qcut_50%,cat_nomi_len_qcut_75%
0,1.993428,3,0,0,1,0,anhalouidine,0,0,0,1
1,0.723471,2,1,0,0,0,joke,1,0,0,0
2,2.295377,1,1,0,0,0,orthobiosis,0,0,1,0
3,4.046060,-1,0,1,0,0,takedown,0,1,0,0
4,0.531693,2,0,0,1,0,becrimson,0,1,0,0

100%|██████████| 11/11 [00:00<00:00, 253.44it/s]00:00, 27.69it/s, Describe variable: cat_nomi_len_qcut_75%]
Summarize dataset: 100%|██████████| 24/24 [00:01<00:00, 23.60it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:02<00:00,  2.34s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  8.63it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 164.48it/s]

# 06_aula_df_biomarc

In [8]:
lista_df[32]

'./data/06_aula_df_biomarc'

In [10]:
load('./data/06_aula_df_biomarc')

ModuleNotFoundError: No module named 'pandas.core.indexes.numeric'

In [12]:
gerador_reporte(c=34)

'./data/06_aula_df_variaveis'

   num_cont num_disc      cat_nomi cat_ordi
0  1.993428      3.0  anhalouidine     midi
1  0.723471      2.0          joke     maxi
2  2.295377      1.0   orthobiosis     maxi
3  4.046060     -1.0      takedown    micro
4  0.531693      2.0     becrimson     midi

100%|██████████| 4/4 [00:00<00:00, 103.34it/s]<?, ?it/s, Describe variable: cat_ordi]
Summarize dataset: 100%|██████████| 14/14 [00:00<00:00, 34.99it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:00<00:00,  1.08it/s]
Render HTML: 100%|██████████| 1/1 [00:00<00:00, 18.49it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 398.36it/s]