In [1]:
# !pip install ydata-profiling util-gfsilveira

In [1]:
import os
from util import utils as ut

from joblib import load, dump
import pandas as pd
from ydata_profiling import ProfileReport

c:\Users\gfsil\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
C:\Users\gfsil\AppData\Local\Temp\ipykernel_32948\2578768081.py:6: DeprecationWarning:
    `import ydata_profiling` is deprecated and will not receive more updates.
    Please install fg-data-profiling via `pip install fg-data-profiling` and use `import data_profiling` instead.

  from ydata_profiling import ProfileReport

In [2]:
lista_df = ["./data/"+i for i in os.listdir("./data") if not i.endswith(".html") and not i.endswith(".txt")]
ut.printLis(lista_df)

-------------
-=< Lista >=-
-------------
0 -> ./data/00_aula_dados
1 -> ./data/00_aula_df
2 -> ./data/00_aula_df_1
3 -> ./data/00_aula_df_2
4 -> ./data/00_aula_df_nova
5 -> ./data/01_aula_dados
6 -> ./data/01_aula_df
7 -> ./data/01_aula_df_1
8 -> ./data/01_aula_df_2
9 -> ./data/01_aula_df_nova
10 -> ./data/04_aula_df_dummies_qcut
11 -> ./data/04_aula_df_final
12 -> ./data/04_aula_df_gera
13 -> ./data/04_aula_df_gera.csv
14 -> ./data/04_aula_df_gera.db
15 -> ./data/04_aula_df_gera_DB.db
16 -> ./data/04_aula_df_no_nan
17 -> ./data/05_aula_df
18 -> ./data/05_aula_df_1
19 -> ./data/05_aula_df_10
20 -> ./data/05_aula_df_11
21 -> ./data/05_aula_df_12
22 -> ./data/05_aula_df_13
23 -> ./data/05_aula_df_14
24 -> ./data/05_aula_df_2
25 -> ./data/05_aula_df_3
26 -> ./data/05_aula_df_4
27 -> ./data/05_aula_df_5
28 -> ./data/05_aula_df_6
29 -> ./data/05_aula_df_7
30 -> ./data/05_aula_df_8
31 -> ./data/05_aula_df_9
32 -> ./data/06_aula_df_biomarc
33 -> ./data/06_aula_df_biomarc.csv
34 -> ./data/06_aula_df_biomarc_ydata
35 -> ./data/06_aula_df_cells
36 -> ./data/06_aula_df_variaveis
37 -> ./data/07_aula_07_df_projeto
38 -> ./data/07_aula_07_df_projeto_estruturada
39 -> ./data/07_aula_07_df_projeto_estruturada.csv

# 04_aula_df_gera

In [8]:
def gerador_reporte(c: int) -> None:
    '''
        Gera um relatório de perfilamento para o dataframe especificado
        pelo índice c na lista de dataframes.
        O relatório é salvo como um arquivo HTML.
            Parametros:
                c (int): Índice do dataframe na lista de dataframes.
            Retorna:
                None
    '''
    df = load(lista_df[c])
    display(lista_df[c])
    display(df.head())
    profile = ProfileReport(df, title="Profiling Report")
    profile.to_file(lista_df[c]+"_report.html")

    return None

In [5]:
gerador_reporte(c=12)

'./data/04_aula_df_gera'

   num_cont num_disc      cat_nomi cat_ordi
0  1.993428      3.0  anhalouidine     midi
1  0.723471      2.0          joke     maxi
2  2.295377      1.0   orthobiosis     maxi
3  4.046060     -1.0      takedown    micro
4  0.531693      2.0     becrimson     midi

100%|██████████| 4/4 [00:00<00:00, 85.44it/s]0<00:00, 38.97it/s, Describe variable: cat_ordi]
Summarize dataset: 100%|██████████| 18/18 [00:00<00:00, 18.21it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:01<00:00,  1.26s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00,  6.46it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 221.22it/s]

# 04_aula_df_no_nan

In [6]:
gerador_reporte(c=16)

'./data/04_aula_df_no_nan'

   num_cont  num_disc      cat_nomi cat_ordi
0  1.993428         3  anhalouidine     midi
1  0.723471         2          joke     maxi
2  2.295377         1   orthobiosis     maxi
3  4.046060        -1      takedown    micro
4  0.531693         2     becrimson     midi

100%|██████████| 4/4 [00:00<00:00, 174.75it/s]<?, ?it/s, Describe variable: cat_ordi]
Summarize dataset: 100%|██████████| 17/17 [00:00<00:00, 31.33it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:00<00:00,  1.46it/s]
Render HTML: 100%|██████████| 1/1 [00:00<00:00, 21.78it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 199.62it/s]

# 04_aula_df_dummies_qcut

In [7]:
gerador_reporte(c=10)

'./data/04_aula_df_dummies_qcut'

,num_cont,num_disc,cat_ordi_maxi,cat_ordi_micro,cat_ordi_midi,cat_ordi_mini,cat_nomi,cat_nomi_len_qcut_min,cat_nomi_len_qcut_25%,cat_nomi_len_qcut_50%,cat_nomi_len_qcut_75%
0,1.993428,3,0,0,1,0,anhalouidine,0,0,0,1
1,0.723471,2,1,0,0,0,joke,1,0,0,0
2,2.295377,1,1,0,0,0,orthobiosis,0,0,1,0
3,4.046060,-1,0,1,0,0,takedown,0,1,0,0
4,0.531693,2,0,0,1,0,becrimson,0,1,0,0

100%|██████████| 11/11 [00:00<00:00, 449.37it/s]00:00, 29.74it/s, Describe variable: cat_nomi_len_qcut_75%]
Summarize dataset: 100%|██████████| 24/24 [00:00<00:00, 32.05it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:01<00:00,  1.65s/it]
Render HTML: 100%|██████████| 1/1 [00:00<00:00, 11.44it/s]
Export report to file: 100%|██████████| 1/1 [00:00<00:00, 250.09it/s]

# 06_aula_df_biomarc

In [3]:
lista_df[33]

'./data/06_aula_df_biomarc.csv'

In [5]:
dump(pd.read_csv(lista_df[33]), "./data/06_aula_df_biomarc_ydata")

['./data/06_aula_df_biomarc_ydata']

In [6]:
lista_df = ["./data/"+i for i in os.listdir("./data") if i.endswith("ydata")]
ut.printLis(lista_df)

-------------
-=< Lista >=-
-------------
0 -> ./data/06_aula_df_biomarc_ydata

In [7]:
gerador_reporte(c=0)

'./data/06_aula_df_biomarc_ydata'

,CD34,TdT,MPO,CD19_1,CD20_1,CD22,CD3_1,CD7,BCR-ABL,PML-RARA,...,IgA_2,IgM,CD16,CD56,DHR,CH50,C3,C4,FOXP3,classe
0,0.119362,True,True,0.471228,0.398837,0.233216,0.329756,0.417118,True,True,...,Alto,Alto,247.894093,396.067195,0.967908,93,230,42,Normal,leucemia
1,0.112420,True,True,0.292042,0.370941,0.253135,0.340733,0.350616,True,True,...,Alto,Alto,213.416161,361.036864,0.972741,135,351,64,Normal,leucemia
2,0.175636,True,True,0.372872,0.257518,0.451758,0.487803,0.399385,True,True,...,Alto,Alto,296.635039,244.867766,0.971384,69,238,44,Normal,leucemia
3,0.078518,True,True,0.469943,0.495637,0.351360,0.332752,0.487439,True,True,...,Alto,Alto,564.401375,530.296010,0.962450,90,262,41,Normal,leucemia
4,0.061083,True,True,0.349343,0.381742,0.220939,0.479723,0.453555,True,True,...,Alto,Alto,238.791009,152.442218,0.955740,76,209,46,Normal,leucemia

100%|██████████| 38/38 [00:00<00:00, 746.55it/s]<00:00, 100.10it/s, Describe variable: classe]
Summarize dataset: 100%|██████████| 532/532 [00:54<00:00,  9.70it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:06<00:00,  6.06s/it]
Render HTML: 100%|██████████| 1/1 [00:03<00:00,  3.81s/it]
Export report to file: 100%|██████████| 1/1 [00:00<00:00,  5.89it/s]

# 07_df_projeto_estruturada

In [4]:
lista_df[39]

'./data/07_aula_07_df_projeto_estruturada.csv'

In [5]:
dump(pd.read_csv(lista_df[39]), "./data/07_aula_07_df_projeto_estruturada_ydata")

['./data/07_aula_07_df_projeto_estruturada_ydata']

In [6]:
lista_df = ["./data/"+i for i in os.listdir("./data") if i.endswith("ydata")]
ut.printLis(lista_df)

-------------
-=< Lista >=-
-------------
0 -> ./data/06_aula_df_biomarc_ydata
1 -> ./data/07_aula_07_df_projeto_estruturada_ydata

In [9]:
gerador_reporte(c=1)

'./data/07_aula_07_df_projeto_estruturada_ydata'

,CD34,NMP22,TP53,IFN-γ,IL-2,TNF-α,Th1,IgG_1,IgA_1,CD3_2,...,CD16,CD56,DHR,CH50,C3,C4,FOXP3,PPD_log,correlatas,classe
0,0.119362,9,0.072077,0.236097,Baixo,Baixo,1219,Alto,Baixo,4777.735596,...,247.894093,396.067195,0.967908,93,230,42,Normal,0.588027,0.417118,leucemia
1,0.112420,7,0.099415,0.195858,Baixo,Baixo,1431,Alto,Baixo,2728.722124,...,213.416161,361.036864,0.972741,135,351,64,Normal,2.400111,0.350616,leucemia
2,0.175636,4,0.206770,0.210132,Baixo,Baixo,876,Alto,Baixo,3496.556667,...,296.635039,244.867766,0.971384,69,238,44,Normal,2.057824,0.399385,leucemia
3,0.078518,4,0.087026,0.111679,Baixo,Baixo,1350,Alto,Baixo,4422.935251,...,564.401375,530.296010,0.962450,90,262,41,Normal,2.230950,0.487439,leucemia
4,0.061083,8,0.154890,0.238945,Baixo,Baixo,647,Alto,Baixo,3021.382901,...,238.791009,152.442218,0.955740,76,209,46,Normal,0.083765,0.453555,leucemia

100%|██████████| 26/26 [00:00<00:00, 5647.14it/s]00:00, 65.05it/s, Describe variable: classe]
Summarize dataset: 100%|██████████| 359/359 [00:41<00:00,  8.73it/s, Completed]
Generate report structure: 100%|██████████| 1/1 [00:07<00:00,  7.24s/it]
Render HTML: 100%|██████████| 1/1 [00:03<00:00,  3.25s/it]
Export report to file: 100%|██████████| 1/1 [00:00<00:00,  5.65it/s]